# Generated by Django 2.0.2 on 2018-02-12 02:23
import json
from django.db import migrations, models


class Migration(migrations.Migration):


    def import_departures(apps, schema_editor):
        fcontent= "" #this is pre-allocated so I can dispose the file as soon as read
        Departure = apps.get_model("departures", "Departure")
        #insert = lambda d: Departure(**d).save()
        try:
            with open("departures.json") as f:
                fcontent = f.read() 
            departures = json.loads(fcontent) # reading and converting to JSON after releasing the resource
            for d in departures:
                dep = Departure(**d)
                dep.save()
            #map(insert,departures)
        except FileNotFoundError as fnf: #JIC the file isn't there
            raise fnf
        except Exception as ex:
            raise ex
        
    

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('category', models.CharField(choices=[('Adventurous', 'Adventurous'), ('Classic', 'Classic'), ('Marine', 'Marine')], max_length=25)),
            ],
        ),
        migrations.RunPython(import_departures)
    ]
