# Generated by Django 2.0.2 on 2018-07-07 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departures', '0001_initial'),
    ]

    operations = [
    ]
